### PR TITLE
changed bg-image

### PR DESCRIPTION
**Pull request by sakshi-choudhary**
added a yellow theme bg image.

### CODE REVIEW

**Comment by ThePsyk3y** [comment]
Could you removeove the .DS_store file? Everything else seems fine.

**Comment by sakshi-choudhary** [comment]
@ThePsyk3y sure

**Comment by sakshi-choudhary** [comment]
@ThePsyk3y check please

**Comment by ThePsyk3y** [comment]
Yes, it's alright now. I'll merge.

**Pull request merged**
